// Hints for practice questions - provide guidance without revealing the answer
export const hintBank: Record<number, string> = {
  // Physics hints
  1: "Think about Newton's second law: F = ma. Divide the force by the mass to find acceleration.",
  2: "Use the kinetic energy formula KE = 1/2 * m * v². Square the velocity first.",
  3: "In a series circuit, add up all resistances. Then use Ohm's law: I = V/R.",
  4: "For parallel resistors, the formula is more complex. Try: 1/Req = 1/R1 + 1/R2.",
  5: "Projectile motion: The vertical component of velocity determines flight time. Use sin(30°) = 0.5.",
  6: "Use the lens formula 1/f = 1/v + 1/u. Rearrange to solve for the image distance.",
  7: "Frequency depends on the spring constant and mass. Check the formula f = (1/(2π))√(k/m).",
  8: "Wave speed depends on tension and linear mass density. Calculate μ first from mass/length.",
  9: "For a circular current loop, use the formula B = μ₀I/(2R) where R is the radius.",
  10: "In series capacitors, the charge is the same on all capacitors. Find the equivalent capacitance first.",
  11: "For isothermal processes with ideal gases, remember P₁V₁ = P₂V₂.",
  12: "Stopping distance: Use v² = u² + 2as with final velocity = 0.",
  13: "Simple pendulum period formula: T = 2π√(l/g). Use l = 1 m.",
  14: "Maximum speed in SHM: vmax = ω × A. Rearrange to find angular frequency.",
  15: "Each half-life cuts the mass in half. How many half-lives are in 30 minutes?",
  16: "Solenoid magnetic field: B = μ₀nI where n is turns per unit length.",
  17: "Faraday's law: emf = N × dΦ/dt. Calculate the rate of change of flux.",
  18: "Coulomb's law: F = kq₁q₂/r². Use k = 9 × 10⁹.",
  19: "Pressure at depth: P = ρgh. Force is pressure times area.",
  20: "De Broglie wavelength: λ = h/p. This relates wave and particle properties.",

  // Chemistry hints
  21: "Convert grams to moles using molar mass. Number of moles = mass/molar mass.",
  22: "At STP, one mole of ideal gas occupies 22.4 L. Multiply by number of moles.",
  23: "Use ΔG = ΔH - TΔS. Watch the signs carefully and convert units.",
  24: "For a second-order reaction, analyze the units from the rate law: rate = k[A]².",
  25: "For strong acids like HCl, the concentration equals [H⁺]. pH = -log[H⁺].",
  26: "For AgCl solubility: Ksp = s². Solve for s in this equilibrium expression.",
  27: "Ligands like NH₃ are neutral. Count the charge from Cl⁻ ions to find oxidation state.",
  28: "Count all C-C bonds, C-H bonds, and identify any double/triple bonds separately.",
  29: "For d-subshell (l=2), use the formula: maximum electrons = 2(2l+1).",
  30: "Exothermic means heat is released. Think about the sign of ΔH.",
  31: "In redox reactions, look for elements that change oxidation state. Which one goes from -1 to 0?",
  32: "Electronegativity increases across a period. Fluorine is in Group 17, period 2.",
  33: "Alkanes are saturated hydrocarbons. Write out the general pattern for CₙH₂ₙ₊₂.",
  34: "Nylon-6 is formed from a 6-carbon ring compound that opens and polymerizes.",
  35: "Same element, different atomic structure. What stays the same vs what changes?",
  36: "Electron sharing is the key characteristic. Which type of bond involves this?",
  37: "Molarity = moles/liters. First convert grams to moles, then divide by solution volume.",
  38: "Tertiary carbocations are most stable. Which option has a carbon bonded to three carbons?",
  39: "Buffers resist pH changes. They need a weak acid and its conjugate base.",
  40: "Think of copper-colored alloys. Brass is used in musical instruments and hardware.",

  // Mathematics hints
  41: "Power rule: d/dx(xⁿ) = n·xⁿ⁻¹. Apply this and substitute x = 2.",
  42: "Use the antiderivative: ∫x² dx = x³/3. Evaluate at the bounds.",
  43: "This is a famous limit. Remember the standard result for sin(x)/x.",
  44: "List all pairs (a,b) where a + b = 9. Count favorable outcomes and divide by 36.",
  45: "For a 2×2 matrix [[a,b],[c,d]], determinant = ad - bc.",
  46: "Dot product: (a₁,a₂,a₃)·(b₁,b₂,b₃) = a₁b₁ + a₂b₂ + a₃b₃.",
  47: "Modulus of a + bi: |z| = √(a² + b²). Square both components and add.",
  48: "Standard circle equation: (x-h)² + (y-k)² = r². Use center and radius.",
  49: "Geometric progression sum: Sₙ = a(1-rⁿ)/(1-r). Check your values of r and n.",
  50: "Combination formula: nCr = n!/(r!(n-r)!). Calculate factorials carefully.",
  51: "The antiderivative of cos(x) is sin(x). Evaluate at π/2 and 0.",
  52: "This is a simple integration problem. Find the antiderivative of 3x².",
  53: "Permutations with repetition: n!/(n₁!×n₂!...). Count repeated letters.",
  54: "tan(45°) = 1 and sec(30°) = 2/√3. Calculate each term separately.",
  55: "Slope formula: m = (y₂-y₁)/(x₂-x₁). Substitute the coordinates.",
  56: "To find inverse: set y = f(x), solve for x, swap x and y.",
  57: "Sum of first n natural numbers = n(n+1)/2. For n = 5, calculate directly.",
  58: "Linear inequality: isolate x. Add 5 to both sides, then divide by 2.",
  59: "Factor the quadratic. Find two numbers that multiply to 6 and add to -5.",
  60: "Standard deck: 4 aces out of 52 cards. Simplify the fraction.",

  // NEET Biology hints (if applicable)
  1001: "Cell structures and their functions vary. Which organelle contains digestive enzymes?",
  1002: "Photosynthesis occurs in the organelle containing chlorophyll. Look for the green pigment location.",
  1003: "During photosynthesis, water is split and a gas is released. Which gas is it?",
  1004: "Hint for additional NEET biology questions would go here as needed.",
};
